#include <iostream>
#include <fstream>
#include <string>

using namespace std;

string Restaurantes[140] = {
        "AJI AMARILLO",
        "AL FRESCO GASTRONOMIA",
        "AL FRESCO PERUANISIMO",
        "ALTO PERU",
        "AMANECER PERUANO",
        "ANTUPERU",
        "AOMORI",
        "ASIA LIMA",
        "ASTRID Y GASTON",
        "ATAHUALPA RESTAURANT",
        "BELLAVISTA",
        "ATAHUALPA RESTAURANT",
        "RECOLETA",
        "BARANDIARAN PROVIDENCIA",
        "BO-DELI",
        "BRISAS DEL MAR",
        "CASONA LIMEÑA PROVIDENCIA",
        "CASONA LIMEÑA RECOLETA",
        "COCOA NAUTICO",
        "COCOA VAGON",
        "COMO EN LIMA",
        "COSTA NAZCA",
        "DAICHI",
        "DE LOS REYES",
        "DONDE GUIDO",
        "DONDE LANDEO",
        "DOÑA TERE CON SABOR",
        "EL CABALLERO DE LOS MARES",
        "EL AJI SECO",
        "EL AJI SECO II",
        "EL CAJAMARQUINO",
        "EL CANTARO DE ORO",
        "EL CHALAN LAS CONDES",
        "EL CHALAN PROVIDENCIA",
        "EL CHE PERUANO",
        "EL CHIMBOTANO",
        "EL ENCUENTRO PERUANO",
        "EL GUSTO PERUANO",
        "EL LIMEÑO FUSIION",
        "EL OTRO ENCUENTRO",
        "EL OTRO PUERTO CALLAO",
        "EL OTRO SITIO ALTO LAS CONDES",
        "EL OTRO SITIO BELLAVISTA",
        "EL OTRO SITIO BORDE RIO",
        "EL OTRO SITIO PARQUE ARAUCO",
        "EL OTRO SITIO PORTAL LA DEHESA",
        "EL PAIJAN",
        "EL PUENTE DE CHABUCA",
        "EL PUENTE DE LOS SUSPIROS",
        "EL TEMPLO DEL INKA",
        "EL VIRREYNATO",
        "EMILIO",
        "GASTRONOMIA PERUANA NELIDA",
        "GRAN MUSEO",
        "HANZO",
        "HIJO DEL SOL",
        "JUANA CRUZ PANTOJA",
        "KATORI",
        "LA CABAÑA DEL INCA",
        "LA CASA DEL CHEFF",
        "LA CASA DEL CHEFF",
        "LA CASONA DE CAJAMARCA",
        "LA CASONA DE LIMA",
        "LA COCINA PERUANA",
        "LA CHOLA SANGUCHERIA BAR",
        "LA CHIKITA I",
        "LA CHIKITA II",
        "LA CHIKITA III",
        "LA ESQUINA LIMEÑA",
        "LA GRAN OLA",
        "LA GRANJA DE FABIÁN",
        "LA LEYENDA DEL AJI SECO",
        "LA MAR CEVICHERIA",
        "LA NORTEÑITA",
        "LAS AMERICAS CONCEPCION",
        "LAS AMERICAS LAS CONDES",
        "LIMA, LIMÓN",
        "LIMA, LIMÓN II",
        "LOS BALCONES DE LIMA",
        "LOS SABORES DEL INCA",
        "LOS TESOROS DEL INCA",
        "LOS TRES CONTINENTES",
        "MACHU PICCHU",
        "MADAM TUSAN",
        "MANE RESTAURANT",
        "MANOS MORENAS",
        "MANOS PERUANAS",
        "MARE NOSTRUM",
        "MARISQUERIA LABRIN",
        "MISKI WASI",
        "MISKI NAUTICA",
        "MOCHICA",
        "MOCHICA RESTAURANT",
        "MUSEO PERUANO",
        "NAZCA CAFÉ- RESTAURANT",
        "OLAN 66",
        "OSAKA",
        "OZAKI",
        "PACHAKAMA",
        "PACHAMAMA",
        "PAIJAN",
        "PANTALEON BELLAVISTA",
        "PANTALEON PROVIDENCIA",
        "PANTALEON SANTIAGO",
        "PARDOS CHICKEN APOQUINDO",
        "PERUANÍSIMO",
        "PERU GUSTOSO",
        "PERU HOUSE",
        "PERU INTERNACIONAL",
        "PERU MAGICO",
        "PERUANÍSIMO",
        "PUERTO CAMARÓN",
        "PUERTO PERU",
        "PUERTO PIRATA",
        "PUERTO PIZARRO",
        "RAYMI",
        "RUINAS DE MACHU PICCHU",
        "SABOR LIMEÑO",
        "SABOR ROCOTO",
        "SABORES DEL PERU",
        "SACSAYHUAMAN",
        "SAZÓN PERUANA",
        "SEÑOR DE SIPAN",
        "SOL (LA REINA)",
        "SOL DE MANCORA",
        "SOL RESTAURANT",
        "SUMAQ MISKI",
        "SUSSHI BLUES",
        "SUSHI HOUSE",
        "SUSPIRO LIMEÑO",
        "TAMBO",
        "TANTA",
        "TANTA",
        "TIERRA NORTEÑA",
        "TRADICIONES PERUANAS",
        "VICTORIA",
        "WARIQUE",
        "OSAKA CEVICHE BAR",
        "LA TASCA DE JUANCHO",
        "LA CARIOCA CEVICHERIA"
};

string Usuarios[140] = {
        "overlordponcy",
        "overlordnaked",
        "overlorditemizer",
        "overlordzone",
        "overlordbalcony",
        "overlordmummy",
        "overlordthap",
        "reliableoverlord",
        "overlordmarvelous",
        "overlordornate",
        "overlordawful",
        "eruptoverlord",
        "overlordoutsmart",
        "compactoroverlord",
        "provinceoverlord",
        "overlordbotch",
        "elsewhereoverlord",
        "overlordwaltz",
        "tarantulaoverlord",
        "overlordmosquito",
        "operativeoverlord",
        "overlordexplosive",
        "overlordcahoots",
        "overlordriver",
        "overlordcivic",
        "overlordcarolina",
        "redoverlord",
        "overlordriveter",
        "snowyoverlord",
        "freehandoverlord",
        "vanquishedoverlord",
        "enrolloverlord",
        "overlordmacho",
        "overlordtrustable",
        "boatoverlord",
        "slushyoverlord",
        "gearoverlord",
        "overlordimmunize",
        "overlordmantalini",
        "bankeroverlord",
        "serveoverlord",
        "overlordautistic",
        "insaneoverlord",
        "overlordunlovable",
        "creepyoverlord",
        "hirdoverlord",
        "overlordreasonable",
        "outeroverlord",
        "upstreamoverlord",
        "overlordreact",
        "skarkoverlord",
        "overlordvalium",
        "overlorddebt",
        "overlorddavid",
        "shoaloverlord",
        "overlordmouldy",
        "overlordgate",
        "overlordguarded",
        "overlordpopper",
        "kidsoverlord",
        "overlordgoosander",
        "bricklayeroverlord",
        "overlordwiping",
        "overlordbitch",
        "mastoverlord",
        "overlordtreat",
        "overlordeasington",
        "westoverlord",
        "overlordeleven",
        "overlordsquacco",
        "staroverlord",
        "socksoverlord",
        "overlordleaf",
        "nevisoverlord",
        "overlordhorn",
        "overlordafterguard",
        "protocolflilux",
        "reanalyzeflilux",
        "fliluxadvice",
        "unplantedflilux",
        "gaspardflilux",
        "fliluxsarming",
        "pendingflilux",
        "hintflilux",
        "fliluxamazing",
        "fliluxcutlery",
        "fliluxrunner",
        "birpingflilux",
        "fliluxzippy",
        "compareflilux",
        "fliluxstreets",
        "fliluxseismology",
        "fliluxwreckage",
        "fliluxslope",
        "fliluxwhen",
        "fliluxalkaline",
        "pilchardflilux",
        "fliluxqualling",
        "fliluxlila",
        "fliluxaverage",
        "thoriumflilux",
        "longflilux",
        "fliluxanimal",
        "fliluxmaverick",
        "sadlyflilux",
        "fliluxlewis",
        "squadflilux",
        "fliluxground",
        "fliluximplosion",
        "bazookaflilux",
        "snowflilux",
        "fliluxcylinder",
        "fliluxcosmetics",
        "fliluxchunks",
        "fliluxupon",
        "hygieaflilux",
        "fliluxdating",
        "strainflilux",
        "headlampflilux",
        "fliluxhelps",
        "fliluxsouthern",
        "esophagusflilux",
        "evaporateflilux",
        "grayflilux",
        "mythflilux",
        "curryflilux",
        "cuspflilux",
        "tuskflilux",
        "fliluxfilk",
        "broomflilux",
        "fliluxcolic",
        "fliluxnitrogen",
        "fliluxproperty",
        "fangflilux",
        "vaguenessflilux",
        "disbandflilux",
        "sourceflilux",
        "nifabs7lackluster",
        "nifabs7pushup",
        "rustnifabs7"
};

string Direcciones[140] = {
        "Avenida Queràs, 94A 5ºD",
        "Carrer Limburguès, 75A 10ºH",
        "Paseo Gasetilles tomàssiu, 278 12ºH",
        "Plaza Sotraguejaries, 7A 12ºE",
        "Ronda Visurada, 211",
        "Urbanización Banyega entenebrem enramàveu, 120 3ºA",
        "Carrer Antiescorbútiques, 106 5ºG",
        "Carretera Gamó enfadàrem columbiana, 17A",
        "Ronda Puntéssem llepolejassin, 221",
        "Cañada Espitllaríeu enventares, 119A",
        "Glorieta Desempouats, 227 5ºA",
        "C. Comercial Carner, 59B 8ºA",
        "Calle Tuberculitzà maculara andaregí africant, 18A 3ºA",
        "Cañada Enamoriscaments borronar, 261A 19ºH",
        "Callejón Tiristor, 177",
        "Glorieta Abrogués avantatgés, 13B 9ºH",
        "Travesía Altiques desembravesquis pugnarà, 62 15ºF",
        "Carrer Fecundis, 65",
        "Rambla Replanat entrevistam aspectuéssem, 129",
        "Calle Esgarrinxares enfadàvem totxana, 76 13ºA",
        "Glorieta Fatxegessis, 88A",
        "Glorieta Insolència pirates aclaparàs qualificaven, 54 10ºC",
        "Urbanización Gal·licana engorgàs apiadarà naixeu, 80 7ºD",
        "Cañada Agrotècnies apassàssiu indisciplinin taulejarà, 205B",
        "C. Comercial Descularíem enfillades compartimentaré condonada, 117",
        "Alameda Focs tronadisses cossoléssim alatxes, 3A",
        "Avenida Envidreeixen mostrejat compartiràs, 109B 7ºC",
        "Calle Esperançara narra, 179A 11ºG",
        "Callejón Dimidiarem, 188B 20ºD",
        "Cuesta Dessolcaves, 172 17ºH",
        "Acceso Nyaufares reivindicareu mainatge, 66",
        "Plaza Liberals investigacions, 41B 10ºC",
        "Vía Estrangeritzàveu llisonin treballuscada, 9A 5ºC",
        "Alameda Antiestètica llavéssiu gessamins vaporis, 133A 2ºG",
        "Avenida Arrenglant fariners estampiu funyiu, 166B 15ºC",
        "Avenida Afavorint banalitzaren mullésseu, 203B 4ºG",
        "Callejón Llisoni emplastre desabrigaràs, 194B",
        "Travesía Boicotessin paredassis, 153A 18ºG",
        "Pasadizo Cistercencs colcaríeu enlluernament redundants, 148A",
        "C. Comercial Bacades esporguinyats, 76 1ºB",
        "Vía Africanista, 70B 15ºC",
        "Camino Fugíem cabdell planessin giletà, 233",
        "Cuesta Entropesso esgarrinxeu, 274 11ºA",
        "Avenida Roquejassin, 299 17ºH",
        "Carrer Ajornaré arxivístic, 118A",
        "Pasaje Octubràveu cavallerejàreu llucarem xaroléssem, 25B",
        "Plaza Calcinéssim immigraven ponguessen encroquesses, 174A 1ºG",
        "Alameda Instal·lava, 71",
        "Avenida Enrodillada pigmentació, 27",
        "Ronda Podalls brueli ennoblí, 134B",
        "Glorieta Remosquejaran, 246A 15ºC",
        "Pasaje Pixidis gaiters, 37 13ºD",
        "Alameda Episodiaries autinianes suprematisme decatides, 195 9ºC",
        "Pasadizo Altejàvem desistirà contrarestaves requisareu, 110B 19ºD",
        "Acceso Pernejaré desespessísseu llaures, 84B 13ºH",
        "Travesía Desenvernissassis, 203A 1ºH",
        "Pasaje Enfloquesses, 274B 13ºE",
        "Pasadizo Ponder, 25A 19ºB",
        "Paseo Assaïnaven vestiré agostassis, 89A",
        "Carrera Esgaripava escumegéssem instituíssiu xacaríeu, 152A 4ºC",
        "Ronda Desencistelléssem grollera ehem ablenant, 222B 15ºA",
        "Urbanización Desenllotaré relativitzaré centreesquerra embalçaràs, 157A 9ºB",
        "C. Comercial Capbaixaren panarrejar mormolàveu, 123B 16ºC",
        "Pasadizo Llosca desertitzàrem conjecturaries oíssim, 224 8ºH",
        "Rambla Aspira converteixin fogonegésseu emmatàrem, 213",
        "Travesía Acolorida matinaries desfalcares, 26 4ºB",
        "Avenida Renyix posttesarien desempegant pilloscara, 17B 20ºF",
        "Ronda Miseracions apergaminéssiu, 155",
        "C. Comercial Especialitzaràs abreviessen, 130B 11ºC",
        "Glorieta Descimalaríeu cabassos flecteixen acuminada, 147 6ºA",
        "Ronda Prisa desperfilau, 204 13ºG",
        "Callejón Subintrants sotmeten espolinaries, 213 18ºH",
        "Alameda Assamarràs, 48A 6ºC",
        "Plaza Noliegéssim encistellem, 197A 10ºA",
        "Rambla Acoquinava, 200A 12ºE",
        "Paseo Encolarien abraça espodasséssem ennegrireu, 203",
        "Carrer Cugucia, 178 19ºH",
        "Travesía Assaborisquen preponderaríeu, 194 16ºC",
        "Travesía Parataxis entremesclareu xocolateries, 257A 12ºA",
        "Pasaje Let dessonillésseu, 287B 4ºH",
        "Cañada Botejàveu afillàssim desemmurrien aborrallone, 195A 12ºD",
        "Callejón Redolara, 28A 8ºG",
        "Acceso Estretíeu escopirem finestregen disgreguessin, 32A 7ºD",
        "Pasadizo Entabuixaran babilònics manxiulots, 144B 19ºF",
        "Pasaje Distorsiones empaní perlejassis liquiditats, 121A",
        "Rambla Desestabilitzaries entelament desarrenguessis estibaré, 254A 4ºE",
        "Glorieta Drenàrem contraent desengalavernat sargeta, 73A",
        "Ronda Empentau arnau suressis requestesses, 208 9ºC",
        "Cañada Antiestàtics desvestires solubilitzares, 201A 20ºB",
        "Calle Estossinaré, 141 18ºF",
        "Rambla Enraso desencistellessen pianoles abiotròfies, 63 16ºH",
        "Alameda Bisellà acloféssiu, 26B 13ºB",
        "Cuesta Insultants billonam irrigàssiu replicàvem, 247A 3ºB",
        "Callejón Profetessen encoixinar arriscaments amen, 59B",
        "Urbanización Implanti ennovaven instrumentalitzassin antracites, 109A 4ºH",
        "Plaza Esguiti eixorbesquis, 256A",
        "Pasadizo Ademussera, 123 16ºH",
        "Cañada Molesti, 118A 14ºF",
        "Alameda Sanguejàssiu defugim telegrafistes durareu, 97A 10ºF",
        "C. Comercial Encalostressen, 109A",
        "Plaza Comunira reexportassis, 231B 5ºB",
        "Cuesta Macere acotxàveu supeditéssem vapora, 208B",
        "Acceso Espifiaran, 25A 17ºB",
        "Glorieta Ajusticiessis, 247A 20ºD",
        "Carrera Descavalcàs prefigurareu empassegats aclameïx, 237 3ºA",
        "Paseo Liofilitzés desapassionaríeu ensalvatgesqui boteria, 245B 3ºE",
        "Plaza Enjudiciada, 235B 3ºB",
        "Calle Descurà costerà brigola, 38B 10ºB",
        "Glorieta Cotní apegarà espurnessis afrontats, 279B 12ºF",
        "Cañada Rails atrèpsies exhauriré, 48B 20ºH",
        "Cañada Pulsativa dèspotes anacardins aquietassis, 203A",
        "Carrer Empunyareu moralitzacions transformàreu encovenàs, 20A",
        "Alameda Fossilitzarà reamputació alçurin roinada, 204 8ºH",
        "Cuesta Esbarzeraran embonaríem atemorides vigilat, 255B 2ºE",
        "Ronda Desencorbarem botanc desgraciaven, 164A",
        "Urbanización Necrosaries esfarinarà, 246",
        "Plaza Físic desmorriareu moldreu despintament, 137A 5ºD",
        "Calle Acondroplàsia, 78 9ºE",
        "Rambla Entrellaçaves, 72",
        "Paseo Enardidors enlleganyéssiu tàtara destarotésseu, 61 6ºC",
        "Pasaje Encabotis, 109B 13ºA",
        "Ronda Pètita, 202 4ºD",
        "Acceso Urceolada, 243A 18ºF",
        "Calle Insidiara temorosa arrengleréssim embenaren, 245B 18ºF",
        "Vía Aboliràs egarenses cal·litricàcia, 66A 8ºG",
        "Camino Escorificàs labiovelaritzés gegantescs malencaminant, 122B 19ºF",
        "Travesía Literaris redreçàreu roborés, 178B 14ºD",
        "Calle Desmentiríem encavalquesses, 197B 20ºA",
        "Paseo Agregaríeu ultrava nodrissa desvesí, 146 2ºA",
        "Vía Pinxejà asserviríeu atenuador, 7B",
        "Ronda Palpam poue atàxica, 127B 15ºF",
        "Carretera Alternatius porres desencordillades, 22 19ºB",
        "Travesía Gèlides ressedimentes congregàssiu, 37B",
        "Travesía Brinden desalineésseu despolititzaven, 224",
        "Travesía Cassaràs psammòfils esclavitzessen salpiques, 41A",
        "Cuesta Agusassin xaloquejar enllardàssim faroleja, 128A 19ºG",
        "Glorieta Desempallarem foliaràs escrues granollerines, 194B 5ºF",
        "Plaza Preguntes emboleu, 164B 3ºH",
        "Pasadizo Esgramaren dretanitzar pendelocs emperesissin, 34A 18ºE",
        "Travesía Abonançàvem intrauterins esmorrassis desarraparies, 194A 16ºE"
};

string Distritos[37] = {
        "Cercado de Lima",
        "Ate",
        "Barranci",
        "Breña",
        "Comas",
        "Chorrillos",
        "El Agustino",
        "Jesús María",
        "La Molina",
        "La Victoria",
        "Lince",
        "Magdalena del Mar",
        "Miraflores",
        "Pueblo Libre",
        "Puente Piedra",
        "Rimac",
        "San Isidro",
        "Independencia",
        "San Juan de Miraflores",
        "San Luis",
        "San Martin de Porres",
        "San Miguel",
        "Santiago de Surco",
        "Surquillo",
        "Villa María del Triunfo",
        "San Juan de Lurigancho",
        "Santa Rosa",
        "Los Olivos",
        "San Borja",
        "Villa El Savador",
        "Santa Anita",
        "Cercado Callao",
        "Bellavista",
        "Carmen de la Legua",
        "La Perla",
        "La Punta",
        "Ventanilla"
};

string Foto[140] = {
        "https://www.example.net/",
        "http://boot.example.com/",
        "http://www.example.com/art.html",
        "https://back.example.edu/#books",
        "https://example.com/air.php",
        "http://www.example.org/air",
        "http://example.com/",
        "https://www.example.com/boy",
        "http://example.com/beef",
        "https://battle.example.com/",
        "http://www.example.com/",
        "https://www.example.com/bite.php#birds",
        "https://www.example.com/?addition=blade",
        "http://www.example.com/aunt.php",
        "https://www.example.com/badge",
        "http://www.example.com/?baby=berry&authority=advice",
        "https://www.example.com/",
        "https://www.example.com/?activity=bridge&addition=behavior",
        "https://example.net/authority?boot=behavior",
        "https://www.example.com/approval",
        "https://www.example.org/",
        "https://angle.example.com/",
        "http://example.com/breath/branch.php#boot",
        "https://www.example.com/bat",
        "http://www.example.net/",
        "https://www.example.org/bite",
        "http://www.example.com/",
        "http://blood.example.com/bikes/apparel?birth=books",
        "http://example.org/?birds=bed",
        "http://www.example.org/bag/animal",
        "https://example.org/",
        "https://example.com/appliance/airplane",
        "https://www.example.com/amount/arithmetic.php",
        "http://www.example.com/bait",
        "http://example.org/",
        "https://example.com/?box=brass&berry=basketball",
        "http://example.com/bike/base#basin",
        "https://apparel.example.com/#bath",
        "http://www.example.org/beef.php",
        "http://www.example.com/bat/act?boat=bee&brake=breath",
        "https://army.example.com/",
        "https://www.example.com/bat",
        "http://example.com/",
        "https://example.com/",
        "http://example.net/brother/breath",
        "http://www.example.com/",
        "https://www.example.com/",
        "http://example.com/",
        "https://attack.example.com/basin?amusement=balance",
        "http://example.org/",
        "http://example.com/",
        "https://badge.example.com/#behavior",
        "http://bat.example.com/branch.htm",
        "https://example.com/",
        "http://www.example.com/basket.html",
        "https://www.example.com/amusement/apparatus.php",
        "http://example.com/",
        "https://example.com/ball/boot?badge=branch",
        "http://www.example.org/?appliance=bikes&bird=breath",
        "https://www.example.com/branch/animal.php?account=beef",
        "http://www.example.com/bedroom?afternoon=book",
        "https://example.com/berry/art.htm?addition=box&arch=attraction",
        "https://www.example.net/?boundary=art",
        "http://www.example.com/bone/arch",
        "https://www.example.edu/",
        "http://www.example.com/",
        "http://www.example.com/account/aftermath.html?border=bite&anger=action",
        "https://www.example.com/beginner/brother",
        "https://example.com/branch.htm",
        "https://authority.example.org/",
        "http://babies.example.com/advertisement.php",
        "http://beds.example.org/believe/argument",
        "https://www.example.com/",
        "https://alarm.example.net/",
        "http://www.example.org/",
        "https://www.example.com/brass/account?bells=agreement&baseball=boot",
        "https://breath.example.org/bird/boundary.php?brick=attack",
        "https://example.com/afternoon",
        "https://example.net/bedroom/bubble.htm",
        "http://www.example.edu/babies/beginner",
        "http://bear.example.org/apparatus.php",
        "https://example.com/battle/basket",
        "http://baseball.example.com/",
        "https://brass.example.com/",
        "https://example.com/",
        "http://www.example.com/apparel?arch=bite",
        "https://www.example.com/",
        "http://example.org/account.html",
        "http://www.example.com/",
        "https://www.example.com/?believe=bead",
        "https://www.example.org/",
        "https://example.com/",
        "https://www.example.com/#army",
        "https://example.com/",
        "http://www.example.com/breath/amount.aspx",
        "http://acoustics.example.com/",
        "https://www.example.net/",
        "https://example.com/amusement/bed",
        "http://example.org/",
        "http://www.example.net/",
        "http://www.example.com/",
        "http://example.com/beginner/addition.aspx",
        "http://basin.example.org/bath",
        "https://www.example.net/boat",
        "https://example.net/",
        "http://www.example.com/",
        "https://example.com/",
        "https://bit.example.com/",
        "https://www.example.edu/afterthought/back.html?bit=berry&beginner=army",
        "https://example.com/baby/actor",
        "http://berry.example.edu/",
        "http://example.com/bedroom.html",
        "https://belief.example.com/",
        "https://afternoon.example.edu/bubble/back.php",
        "http://www.example.com/beef/ants.aspx",
        "https://www.example.com/",
        "https://www.example.com/",
        "http://books.example.com/?army=book&birthday=brass",
        "https://www.example.com/boat.html",
        "https://www.example.com/basket",
        "http://example.org/",
        "http://bait.example.edu/arithmetic",
        "https://example.com/",
        "http://www.example.com/",
        "http://www.example.com/boot/attack.php",
        "https://www.example.com/#birthday",
        "https://www.example.com/#breath",
        "https://example.com/blood?bear=bag",
        "https://basin.example.com/act.php",
        "http://www.example.edu/",
        "http://border.example.com/",
        "http://www.example.net/bag#brick",
        "https://www.example.com/?bear=bubble",
        "http://example.com/",
        "http://www.example.net/",
        "http://army.example.com/aftermath.aspx",
        "http://example.com/",
        "http://www.example.com/",
        "https://www.example.com/act.html?basket=adjustment#brick",
        "https://afterthought.example.com/"
};

int main() {
    fstream Generador;
    Generador.open("../Insertar_restaurantes.sql", ios::out);
    if (!Generador.is_open()) {
        cout << "Error en la exportacion" << endl;
        exit(EXIT_FAILURE);
    }
    for (int i = 0; i < 140; ++i) {
        Generador << "INSERT INTO RESTAURANTE (RUC, USERNAME, DIRECCION, NOMBRE_RESTAURANTE, DISTRITO, FOTO_FACHADA)" << endl;
        Generador << "VALUES ('" << 17358452744 + i << "', '" << Usuarios[i] << "', '" << Direcciones[i] << "', '" << Restaurantes[i] << "', '" << Distritos[i%37] << "', '" << Foto[i] << "');" << endl;
    }
    return 0;
}